# Server properties
server:
  port: 8080
  servlet:
    context-path: /BeerApp
  
spring:
  # JPA properties
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    generate-ddl: true
  # Datasource properties
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      pool-name: JPAHikariCP
      connection-timeout: 20000
      idle-timeout: 20000
      max-lifetime: 100000
  # In-memory H2 database properties
  h2:
    console:
      enabled: true
      path: /h2-console
      
# Logging properties      
logging:
  level:
    org.hibernate.SQLQuery: debug
    org.hibernate.type.descriptor.sql: trace
    